### ISSUE TITLE
[Feature] FlaggedTransaction Controller (Ruben Brinkman)

### ISSUE THREAD

**Issue by GEWISabc** [GEWIS/sudosos-backend#10]
The flagged transaction controller should do all things related to flagged transactions.

- [x] POST flagged transaction
- [x] PUT flagged transaction
- [x] GET all flagged transacions
- [x] GET flagged transaction by ID
- [ ] GET flagged transactions by Status
- [ ] GET flagged transactions by Transaction
- [x] Pagination

**Comment by rinkp** [comment]
Considering the relatively high amount of tickets that we receive with 'this is not my transaction', do we want to adjust the priority of implementing this @CodeNamedRobin @JustSamuel

**Comment by CodeNamedRobin** [comment]
I also think the GET flagged transactions by Transaction is really unnecessary.

**Comment by JustSamuel** [comment]
Will not be implemented.
