### ISSUE TITLE
Borrelkaart + BorrelkaartGroup controller (Ruben Brinkman)

### ISSUE THREAD

**Issue by GEWISabc** [GEWIS/sudosos-backend#11]
Even though borrelkaarten are a special type of users it might still be useful to have some specific logic for them in a special controller.

- [ ] GET all borrelkaarten
- [ ] GET all borrelkaarten that are not in a borrelkaartgroup
- [ ] GET borrelkaarten by BorrelkaartGroup
- [ ] Create batch of Borrelkaarten by creating BorrelkaartGroup with a number of cards and start saldo
- [ ] Add borrelkaarten to borrelkaart group

All the other things regarding borrelkaarten should be implemented as user logic.

**Comment by Yoronex** [comment]
All endpoints have been implemented.
