### ISSUE TITLE
[Request] Add link to debtor mails

### ISSUE THREAD

**Issue by CodeNamedRobin** [GEWIS/sudosos-backend#134]
It would be nice if people could immediately go to SudoSOS when they get noticed they're in debt.

**Comment by JustSamuel** [comment]
see [98](https://github.com/GEWIS/sudosos-backend/pull/98)

**Comment by rinkp** [comment]
There already is a link in the signature. If you are adding a link, the best thing to do would be to make sure that the link is formatted as `<a href=https://XXXX/YYYY'>https://XXXX/YYYY</a>`
not as `<a href='https://sudosos.gewis.nl/topup'>sudosos.gewis.nl</a>` as that might get you marked as phishing
and definitely avoid `<a href='https://stripe.gewis.nl/paymentxx'>sudosos.gewis.nl</a>` as that **will** get you marked as phishing

**Comment by tomudding** [comment]
https://github.com/GEWIS/sudosos-backend/pull/98#issuecomment-2125340568
