### ISSUE TITLE
Typo in the mail

### ISSUE THREAD

**Issue by SuperVK** [GEWIS/sudosos-backend#136]
There is a slight typo in https://github.com/GEWIS/sudosos-backend/blob/develop/src/mailer/templates/user-debt-notification.ts#L60 where accoring should be according.

**Comment by rinkp** [comment]
Please then also fix 

[into the future](https://github.com/GEWIS/sudosos-backend/blob/develop/src/mailer/templates/user-debt-notification.ts#L62C1-L62C122)
It would be pretty cool to time travel, but maybe not as a punishment

```diff
-<p>Go to the SudoSOS website to deposit money into your account. With this you prevent getting fined into the future.</p>
+<p>Go to the SudoSOS website to deposit money into your account. With this you prevent getting fined in the future.</p>
```
