### ISSUE TITLE
Deleting a fine, resulting in positive balance, doesn't remove fine status

### ISSUE THREAD

**Issue by CodeNamedRobin** [GEWIS/sudosos-backend#137]
Situation: A user has multiple fines and has a balance just under 0. One fine is deleted, putting the user in a positive balance.
Expected: The user has all fines marked as paid off.
Actual: The user is still in a fined status.
Proof:
![WhatsApp Image 2024-01-12 at 18 52 11_51c1716c](https://github.com/GEWIS/sudosos-backend/assets/12692018/423d9ec0-d052-4056-938e-212c873c44e4)
![image](https://github.com/GEWIS/sudosos-backend/assets/12692018/f77256c0-ae7e-4375-a566-5091e5b78db7)

**Comment by JustSamuel** [comment]
Clearly the easier solution: https://github.com/GEWIS/sudosos-frontend-vue3/tree/bugfix/hide-fine-on-positive

**Comment by Yoronex** [comment]
Should in my opinion still be resolved on the backend, because it will also show on the "Schandpaal" in the room
