### ISSUE TITLE
Avoid duplicate emails for fines

### ISSUE THREAD

**Issue by rinkp** [GEWIS/sudosos-backend#143]
Currently, users that have been fined will receive both an email 
- that they have been fined
- that they will be fined next week if they don't top up

While I think it is important that users are reminded of a negative balance often, I think this might be a bit superfluous and I would suggest not sending the latter if you just sent the former (i.e. added a fine the past day

Moreover, sending two emails in a short while may cause behaviour where the spam filter of the recipient is checking whether it will receive more email from GEWIS for determining the likelihood of spam and we actually send them these emails.

Additionally, you might want to consider sending the second email even if you don't really add fines, such as during the exam week.

**Comment by CodeNamedRobin** [comment]
Personally, I think this might be a better idea to implement in the frontend? Both notify and handout endpoints have userIds parameters in their requests. How I could keep track of if users got an email recently (probably same day?) I don't really know, but that's a problem for later.

**Comment by Yoronex** [comment]
We leave this issue to the frontend, as the BACPM is the one giving the list of users to notify to the backend. https://github.com/GEWIS/sudosos-frontend/issues/361
