### ISSUE TITLE
Improve production logging and make it (more) persistent.

### ISSUE THREAD

**Issue by JustSamuel** [GEWIS/sudosos-backend#154]
Our current logging setup is dumping everything in stdout [(which is not bad)](https://12factor.net/logs). However, I think we should move to a more insightful setup that allows is to effectively search our logs and be better able to trace when something goes wrong.

Maybe something like an [ELK](https://github.com/deviantony/docker-elk) setup?

**Comment by rinkp** [comment]
I think the current setup is easy to use for both development and in production. If there is need for improved logging, you can consider changing the logging globally on the docker server to be more persistent.

**Comment by rinkp** [comment]
If you want to go this route, you most likely can reuse the configuration that we use for keycloak and ingest data to elastic-ingest.localnet.gewis.nl to make it available on kibana.gewis.nl
