### ISSUE TITLE
[Feature Request] Endpoint to generate a fine overview

### ISSUE THREAD

**Issue by CodeNamedRobin** [GEWIS/sudosos-backend#155]
As the BAC treasurer needs to book in the fines (and would probably do this monthly), it would be good to have a way to get an overview of the amount of fines that we're dished out in a certain time period. This would in my opinion be very similar to the current transaction report feature, although that is for all users, and this feature is specific to the BAC treasurer.

**Comment by JustSamuel** [comment]
Endpoint for the report in the form of a json is in PR #189, pdf will have to wait a for a bit.

**Comment by JustSamuel** [comment]
PDF generation is currently live, re-open if you are missing something.
