### ISSUE TITLE
Useful that all transactions/transfers endpoints return PaginatedFinancialMutationResponse

### ISSUE THREAD

**Issue by SuperVK** [GEWIS/sudosos-backend#157]
Currently all certain endpoints such as users/{id}/transfers or users/{id}/transactions currently return PaginatedTransferResponse and PaginatedBaseTransactionResponse. However these are usually all handled in the same way by the frontend. So even though it seems a bit weird because it is already guaranteed that the type of each transaction/transfer is one or the other, it is easier to change these all to PaginatedFinancialMutation. This way calls from both users/{id}/transfer and pointofsale/{id}/transactions can all be handled as the same type, and be rendered in the exact same component without weird type guarding.

**Comment by JustSamuel** [comment]
@Yoronex opinion?

**Comment by Yoronex** [comment]
I prefer not to do this, as the PaginatedFinancialMutation response adds a lot (and I mean _a lot_ to the separate endpoints). I see that it is easier for the frontend to handle as you no longer need to map all these objects there, but I am not convinced that it outweighs the extra bloat that we have to add to those respective endpoints.

**Comment by SuperVK** [comment]
oh I thought i already closed this, I solved this in another way that works much better :)
