### ISSUE TITLE
Mailing BAC PM for payout request

### ISSUE THREAD

**Issue by SuperVK** [GEWIS/sudosos-backend#158]
When a payout request has arrived, it might be nice to notify the BAC PM that there has been a payout request made, by for example mailing bacpm@gewis.nl.

**Comment by SuperVK** [comment]
Do we still want this now that the frontend a notification bubble for the payouts?

**Comment by JustSamuel** [comment]
Closing since I don't think we will implement this anymore with the notification bubbels.
