### ISSUE TITLE
[BUG] Fines without warning in some situations

### ISSUE THREAD

**Issue by rinkp** [GEWIS/sudosos-backend#159]
Consider the following scenario:

1. During borrel *x*, the user has a balance of -€4,-, so they don't get an email that they will be fined next week
2. The user buys two beers
3. During borrel *x+1*, the user has a balance of -€6,-, so the user is fined €1,-

Solution 1 (my preference):

1. The user receives a notification that their balance is negative and that if they have a balance <-€5 next week, they will receive a fine

Solution 2 (alternative);

1. The user does not receive a fine in week *x+1*, but only in week *x+2*

**Comment by rinkp** [comment]
Example:

User 14595 did not receive a warning on March 21st, but did receive a fine on March 28th

**Comment by CodeNamedRobin** [comment]
Hi Rink, solution 1 is already how we do it, but I didn't hand out fines on March 21st as there was an outage at ABN AMRO.

**Comment by rinkp** [comment]
Check
