### ISSUE TITLE
[Feature]: Soft-lock users with high fines

### ISSUE THREAD

**Issue by JustSamuel** [GEWIS/sudosos-backend#194]
### What would you like?

When a user has a negative balance of > 20 they should be unable to buy anything until they top up. This can be combined with a warning / info message on both the POS and the Dashboard so that they don't go stealing.

### How could it be implemented?

Add an extra column to the user `defaulter` which if true acts like  `canGoIntoDebt: false` but also allows us to notify the user. 

TODO
- [x] Implement `defaulter` column
- [x] `defaulter` should be set to true if user has more than 20 euro negative balance
- [ ] Add this change to the TOS
- [x] `defaulters` are only allowed to topup
- [ ] Implement notification on the POS + Website
- [ ] Send a separate e-mail notifying user of their `defaulter` status

### Related
[#ABC-2409-448](https://support.gewis.nl/scp/tickets.php?id=22319)

**Comment by JustSamuel** [comment]
Bumped priority because of ticket #ABC-2409-448 and that I foresee more issues like this. Having fewer people in the minus might be a good start.

**Comment by rinkp** [comment]
Not all users should be banned from purchasing when <-€20. Invoice users should not be disallowed from purchasing, also perhaps you want to distinguish: bought 2 meters of beer tonight and has never paid since they became a member and now is at -€20

**Comment by SvenMokveldje** [comment]
After the SudoSOS meeting, we have decided to not continue this feature.
The minutes of this meeting can be found here: [https://support.gewis.nl/scp/tickets.php?id=22960]([#ABC-2410-173](https://support.gewis.nl/scp/tickets.php?id=22960))
