### ISSUE TITLE
Return HTTP 204 instead of 200 when returning an empty body.

### ISSUE THREAD

**Issue by GEWISabc** [GEWIS/sudosos-backend#21]
**Description:**
Currently, our API handles DELETE requests for certain routes, such as DELETE /banners/{id}, by returning a response with an HTTP status code of 200 along with the deleted entity in the response body. However, according to HTTP standards, DELETE requests that have been successfully processed should return an HTTP status code of 204 with an empty response body.

**Task:**

- Modify the DELETE route handlers to return an HTTP status code 204 (No Content) upon successful deletion, signaling that the resource has been removed.
- Remove any unnecessary response data from the body of DELETE responses, ensuring they are empty as per the HTTP specification.
- Update relevant documentation or API descriptions to reflect this change in behavior.

**Expected Outcome:**
By addressing this issue, we aim to align our API responses with industry best practices and HTTP standards. This change will improve the consistency and correctness of our API, making it more intuitive for developers and clients consuming our services.

**Skills Required:**
- Backend development
- Familiarity with HTTP status codes and RESTful API design

**Difficulty Level:**
Beginner

**Additional Information:**
This issue is an excellent opportunity for contributors to participate in Hacktoberfest and make a meaningful contribution to our project. Feel free to ask any questions or seek guidance on how to implement the suggested changes. Your efforts will help improve the quality of our API and enhance the overall user experience.

**Comment by JoHeyJo** [comment]
I PR a few changes. Is this what you had in mind? [https://github.com/GEWIS/sudosos-backend/pull/81](url)

**Comment by JustSamuel** [comment]
Yeah! Something like that.
