### ISSUE TITLE
[Feature] Filtering financial mutations fromDate and tillDate

### ISSUE THREAD

**Issue by SuperVK** [GEWIS/sudosos-backend#213]
### What would you like?

It would be nice to be able to filter the financial mutations on fromDate and tillDate (including time of day)

### Why is this needed?

For cases where you want to filter financialmutations from for example an invoice account to only have the transactions for an specific date. Or if you want to know how much you spent during a borrel. 

### How could it be implemented?

Like the /transactions endpoint also implements this (I hope)

**Comment by Yoronex** [comment]
Implemented in https://github.com/GEWIS/sudosos-backend/pull/227
