### ISSUE TITLE
[Bug] RBAC does not allow fetching transactions created by signed-in user

### ISSUE THREAD

**Issue by rinkp** [GEWIS/sudosos-backend#264]
### Current behavior

SudoSOS frontend attempts to fetch the following URL
`/api/v1/transactions?createdById=[currentSignedInUser]&take=10&skip=0`

Not all users have permissions to fetch transactions they created themselves. 

### Desired behavior

Either the frontend should not fetch this, or the backend should allow this. 

### API Route

/api/v1/transactions?createdById=[currentSignedInUser]&take=10&skip=0

### Steps to reproduce

.

### Logs and Error Messages

`You have insufficient permissions for the requested action.`

### Other Information

Happens on sudosos.gewis.nl and sudosos-beta.gewis.nl

**Comment by SuperVK** [comment]
This happens specifically for local users I think

**Comment by rinkp** [comment]
> This happens specifically for local users I think

I am unsure how you reach this conclusion since I am not a local user, yet it happens on my account.

**Comment by SuperVK** [comment]
Ah wait yeah, I forgot that my "normal" account has all rights. I came to this conclusion cause my testing local user which has no permissions, so I assumed a while back that this was a local user issue

**Comment by Yoronex** [comment]
This is because SudoSOS frontend uses the wrong endpoint. The `/api/v1/transactions` endpoint requires one to have permissions to access _all_ transactions, while the `/api/v1/users/{id}/transactions` endpoint requires one to have permissions to access your _own_ transactions. This is therefore expected and not a bug.
