### ISSUE TITLE
Not all logs are logged

### ISSUE THREAD

**Issue by tomudding** [GEWIS/sudosos-backend#265]
### Current behavior

Directly related to ABC-2408-195 (and a bit GH-154). Only one worker's logs are outputted to stdout, logs from all other workers do not appear.

### Desired behavior

All logs are merged (perhaps distinguishable by a thread/worker id) and outputted.

### Steps to reproduce

Check Portainer, many logs (transactions are the easiest to see) are not present.

### Logs and Error Messages

They are not there...

**Comment by JustSamuel** [comment]
Fixed by #303
