### ISSUE TITLE
[BUG] GET /users/ return different results everytime

### ISSUE THREAD

**Issue by CodeNamedRobin** [GEWIS/sudosos-backend#273]
### Current behavior

Currently, when requesting anything from an endpoint that implements pagination, results differ every time.

### Desired behavior

I expected to get the same response every time I execute a request.

### API Route

GET /users/

### Steps to reproduce

1. Go to the Swagger
2. Authenticate yourself
3. Go to the GET /users/ endpoint
4. Execute a request
5. Observe the response
6. Execute the same request
7. Observe a different response.

**Comment by Yoronex** [comment]
Can you please be more specific? I have tried this with the `GET /transactions` endpoint and I could not replicate the issue.

**Comment by CodeNamedRobin** [comment]
Sorry, endpoint has been updated in the original user.
