### ISSUE TITLE
[Bug]: Public key for authentication gewisweb not working

### ISSUE THREAD

**Issue by SuperVK** [GEWIS/sudosos-backend#286]
### Current behavior

https://sudosos.test.gewis.nl/api/v1/authentication/gewisweb returns nothing

### Desired behavior

It should return the relevant authentication public token like the spec says

### API Route

GET /api/v1/authentication/gewisweb

### Steps to reproduce

run:
`curl -X 'GET' \
  'https://sudosos.test.gewis.nl/api/v1/authentication/gewisweb' \
  -H 'accept: application/json'` 
or use your browser or the swagger, and observe nothing gets returned.

**Comment by Yoronex** [comment]
Interesting problem, as the endpoint on `sudosos-test` works just fine... Maybe after update `0.6.0` the issue might resolve itself. It does seem to be a problem in `sudosos-prod` though.

**Comment by Yoronex** [comment]
It seems to work now? No clue what was going on...
