### ISSUE TITLE
Request validator using swagger-model-validator

### ISSUE THREAD

**Issue by JustSamuel** [GEWIS/sudosos-backend#44]
Since we already use swagger-model-validator I propose to use [the built in extra validation](https://github.com/swagger-model-validator/swagger-model-validator#custom-field-validators) instead of our custom validators.

This means refactoring most of the custom validators and moving those to the swagger-model-validators.

**Comment by Yoronex** [comment]
Another option would be to use the widely-used `express-validator` package (in combination with `validate.js`). This library seems very easy to use and supports overriding the default class, so we can easily add global validation (chains) ourselves. https://express-validator.github.io/docs/guides/customizing#typescript-support

**Comment by JustSamuel** [comment]
I would like something tied into our Swagger as it enforces correctness of our API docs and stuff.

**Comment by JustSamuel** [comment]
Duplicate of #116
