### ISSUE TITLE
Swagger doc/spec seems to be a bit inconsistent

### ISSUE THREAD

**Issue by CodeNamedRobin** [GEWIS/sudosos-backend#71]
The Swagger documentation seems to be a bit inconsistent/incorrect. Already seen with the debtors endpoint, but small inconsistencies like the patch user endpoint mentioning 'new user' are still in there as well. This seems like a good issue to be fixed during Hacktoberfest.

**Comment by JustSamuel** [comment]
Closing because this is too vague to solve.
