### ISSUE TITLE
Fix Invoice Filtering Bug in `GET /invoices` Endpoint 

### ISSUE THREAD

**Issue by CodeNamedRobin** [GEWIS/sudosos-backend#77]
**Description:**
Our API endpoint GET /invoices offers functionality to filter invoices based on their state, allowing users to retrieve invoices that fall into categories such as CREATED, SENT, PAID, or DELETED. However, there is a bug in this feature - regardless of the state provided in the request, the endpoint returns all invoices without proper filtering.

**Task:**
- Investigate the GET /invoices endpoint to identify the root cause of the filtering issue.
- Implement a fix to ensure that the endpoint correctly filters invoices based on the specified state parameter, returning only invoices that match the selected state.
- Update relevant documentation, if needed,  to reflect the corrected behavior of the endpoint.

**Expected Outcome:**
By addressing this issue, we aim to enhance the functionality and accuracy of our API by resolving the bug in the invoice state filtering. This will provide a more reliable and intuitive experience for our users, ensuring that they can retrieve the specific invoices they need.

**Skills Required:**
- Backend development
- Knowledge of API endpoints and query parameter handling
- Debugging and issue resolution

**Difficulty Level:**
Beginner

**Additional Information:**
This issue is an excellent opportunity for Hacktoberfest participants to contribute to our project by fixing a simple bug that impacts the invoice filtering feature. If you have any questions or need guidance on how to approach this task, please don't hesitate to ask. Your efforts will help improve the overall functionality and usability of our API.

**Comment by JustSamuel** [comment]
Actually not as straight forward as I hoped.

`currentState` is a computed property, i.e. the state of the last InvoiceState. This means that filtering isn't very straight forward. 

A solution would most likely require rewriting the getInvoices into a queryBuilder which also isn't preferred.
