### ISSUE TITLE
TypeORM synchronize failing on MySQL due to NFCAuthenticator

### ISSUE THREAD

**Issue by Yoronex** [GEWIS/sudosos-backend#83]
When trying to synchronize the database schema in a MySQL database instance, TypeORM throws an error about a duplicate index. This seems to be caused by the `NFCAuthenticator` entity. Other authenticators do somehow not have this issue, because they are instances of `HashAuthenticator`. Even though it might not provide many benefits, it would resolve this issue and make the codebase more consistent if `NFCAuthenticator` also extends from `HashAuthenticator`. Currently, NFC is not yet used in production, so we can safely change this entity.

**Comment by JustSamuel** [comment]
Member authenticator had the exact same bug; I had to manually change the indexing / keys of the production database.

**Comment by Yoronex** [comment]
Member authenticator is unfortunately also not correct when synchronizing the database, because TypeORM adds a "unique" constraint to the `userId` column, meaning that every user can have at most 1 member authenticator. 

![image](https://github.com/GEWIS/sudosos-backend/assets/38660000/4f4fa486-571c-4d02-9b6f-312f7ee35e2c)

Maybe we should just accept that these entity structures (with extended classes, composite keys and indices) are too complex for TypeORM. Adding a primary incremental key will break the normalization of the schema, but will probably resolve all these issues.

**Comment by JustSamuel** [comment]
Does my fix on the [mysql-schema-seed](https://github.com/GEWIS/sudosos-backend/tree/bugfix/mysql-seed-schema) branch work?
