### ISSUE TITLE
GET /balances/all cannot filter based on UserType

### ISSUE THREAD

**Issue by Yoronex** [GEWIS/sudosos-backend#84]
This field is ignored when supplying it with either integers or full names. Somehow, the test cases do seem to pass, so something is going wrong with parsing. Probably related with https://github.com/GEWIS/sudosos-backend/issues/77.

**Comment by JustSamuel** [comment]
Solution is linked to https://github.com/GEWIS/sudosos-backend/issues/19

**Comment by CodeNamedRobin** [comment]
On main, on which this #121 is already merged, this still does not work.
