### ISSUE TITLE
Implement Expending of request objects.

### ISSUE THREAD

**Issue by JustSamuel** [GEWIS/sudosos-backend#87]
When requesting certain objects, such as user balance's, you will not get all the user info back. This is to make the responses lightweight by prefer to give less and let the user make more requests when more info is needed. However, in some cases we lack the ability to requests a larger set of data (i.e., give me all users with these ID's).

[Stripe allows API users to expend responses](https://stripe.com/docs/api/expanding_objects). I think this is the best approach if we ever want to do this nicely. For even more info check[ this docs](https://stripe.com/docs/expand).

**Comment by Yoronex** [comment]
This does indeed look nice, but wouldn't a basic store in a frontend that keeps a list of users with their names, types and IDs also solve the problem? I do agree that it would be nice to have the corresponding names of the users in some queries (like getting balances), but that will also add some extra complexity. In the OpenAPI spec, the user object will then have to be optional, so we explicitly have to document when one will receive those objects. For queries that use `QueryBuilder` or even bare SQL queries like balances, it will make the query even larger and more complex to understand and process.

Something to think about / discuss with the ABC.

**Comment by JustSamuel** [comment]
Might be nice to just implement an optional param for the balance queries to add the associated user? Since this is the only place where this is a major issue, as most other controllers simply return expanded objects?

If you agree I'll close this issue and create a new one.

**Comment by Yoronex** [comment]
Yes, let's do that.
