### ISSUE TITLE
Feature Request: Overdue Invoices Endpoint

### ISSUE THREAD

**Issue by CodeNamedRobin** [GEWIS/sudosos-backend#89]
Right now there is no differentiation between invoices that are overdue and those that are not, which would be a very nice addition to have for the BACPM.

**Comment by Yoronex** [comment]
SudoSOS currently does not store any expiry date. This will therefore need to be added first. Maybe we can "borrow" some work from ParelPracht.

**Comment by CodeNamedRobin** [comment]
Alright, this might be a good idea. With this it may be nice to combine it into #90.

**Comment by JustSamuel** [comment]
[SudoSOS is not bookkeeping software.](https://github.com/GEWIS/sudosos-backend/issues/260#issuecomment-2291429901)
