### ISSUE TITLE
Invoice Addressees are primitive

### ISSUE THREAD

**Issue by CodeNamedRobin** [GEWIS/sudosos-backend#90]
Right now an addressee is a simple string. This is not complete enough since the addressee consists of an organisation, person and address. This should be reflected in the InvoiceResponse, preferably in a type for an addressee consisting of all this data.

**Comment by Yoronex** [comment]
SudoSOS knows to whom the invoice is addressed, because it has a reference to a user. From what I understand, you also want SudoSOS to act as a general invoice generator and manager, like ParelPracht?

**Comment by CodeNamedRobin** [comment]
I do think it might be nice to have some more complications in addressing, yes, as right now when generating an invoice (in PDF) from the returned JSON, it defaults to the GEWIS PM, which is a generalisation that is not valid. As I see, there are two options for this. 
1. We create this feature in the SudoSOS backend and use that in the front-end.
2. We create this feature purely in the front-end, and then send this info along with the invoice JSON response to the PDF-generator to create a full invoice.

In my opinion, option 1 creates for a more solid and thorough approach.
