### ISSUE TITLE
Invoice PATCH does not respond with the updated invoice, as per the spec

### ISSUE THREAD

**Issue by CodeNamedRobin** [GEWIS/sudosos-backend#91]

**Comment by Yoronex** [comment]
Please provide a step-by-step description on how to reproduce the issue. What is expected as a response and what is the actual response? Why is this incorrect?

**Comment by CodeNamedRobin** [comment]
Steps to reproduce:
1. Go to the swagger UI or find another means to call the API.
2. Do an API call on PATCH /invoices/{id}
3. Look at the response

Expected response: The updated invoice.
Actual response: An empty 200 response.

**Comment by rinkp** [comment]
Before considering this issue, you want to make a standard for all `PUT` and `PATCH` requests in `sudosos-backend`

[RFC5789](https://www.rfc-editor.org/rfc/rfc5789.html) leaves open whether you need to respond with something
![image](https://github.com/GEWIS/sudosos-backend/assets/17340320/5ed38b21-823c-4177-89ba-78db7b0a2a7d)

[Google standards](https://cloud.google.com/apis/design/standard_methods#update) demand the full object to be returned
![image](https://github.com/GEWIS/sudosos-backend/assets/17340320/2858a46f-5e07-4dda-8ef2-5cf333a1a16f)

[Microsoft's REST standard](https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md) explicitly forbids returning a body in a PATCH
![image](https://github.com/GEWIS/sudosos-backend/assets/17340320/af17b134-37ba-485c-a07c-8fd0fa82932e)

**Comment by Yoronex** [comment]
We currently return always return the updated entity. Only for `DELETE` operations or operations that perform actions on the backend, we return an empty body.

**Comment by CodeNamedRobin** [comment]
Closed as cause has been found and moved to #107.
