### ISSUE TITLE
Invoice PATCH is slow and inconsistent

### ISSUE THREAD

**Issue by CodeNamedRobin** [GEWIS/sudosos-backend#92]
For example when updating the state of the invoice, it does not update at all, or not immediately. This means the endpoint is very unreliable and frankly unusable.

**Comment by Yoronex** [comment]
Please provide a step-by-step description on how to reproduce the issue. What is expected as a response and what is the actual response? Why is this incorrect?

**Comment by CodeNamedRobin** [comment]
Steps to reproduce:
1. Go to the Swagger UI or find another means to do an API call.
2. Get an invoice that you want to edit via a GET invoices/{id} API call, and copy it's id.
3. Patch it with a PATCH invoices/{id} API call.
4. Redo step 2.

Expected response: The original invoice, with the updated data that was put in on step 3.
Actual response: Mixed, sometimes it does have the updated data, sometimes it doesn't. Sometimes it only has the updated data after some time.

**Comment by CodeNamedRobin** [comment]
Closed as cause has been found and moved to #107
